branch-defaults:
  master:
    environment: vixay-env
    group_suffix: null
environment-defaults:
  vixay-env:
    branch: null
    repository: null
global:
  application_name: vixayWebsite
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
